# Generated by Django 3.1.7 on 2021-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0003_auto_20210314_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
