# Generated by Django 3.1.7 on 2021-03-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0006_auto_20210314_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
