# Generated by Django 3.1.7 on 2021-03-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0010_auto_20210314_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='initiator',
            field=models.ForeignKey(db_column='initiator', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.user'),
            preserve_default=False,
        ),
    ]
