# Generated by Django 3.1.7 on 2021-03-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0014_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.user'),
        ),
    ]
