# Generated by Django 3.1.7 on 2021-03-14 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0015_domain_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
