# Generated by Django 3.1.7 on 2021-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0016_auto_20210314_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='info',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
