# Generated by Django 3.1.7 on 2021-03-14 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0018_userfriend_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('from_user', models.ForeignKey(db_column='from_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user', to='restapis.user')),
                ('to_user', models.ForeignKey(db_column='to_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user', to='restapis.user')),
            ],
            options={
                'db_table': 'user_chats',
            },
        ),
    ]
