# Generated by Django 3.1.7 on 2021-03-14 19:46

from django.db import migrations


def make_genders(apps, schema_editor):
    Gender = apps.get_model("restapis", "Gender")
    values = ["Male", "Female", "Transgender", "Other"]
    for x in values:
        gender = Gender.objects.filter(value=x).count()
        if gender == 0:
            Gender.objects.create(value=x)


def make_statuses(apps, schema_editor):
    Status = apps.get_model("restapis", "Status")
    values = ["Blocked", "None", "Pending", "Connected"]
    for x in values:
        status = Status.objects.filter(value=x).count()
        if status == 0:
            Status.objects.create(value=x)


class Migration(migrations.Migration):

    dependencies = [
        ("restapis", "0019_userchats"),
    ]

    operations = [
        migrations.RunPython(make_genders),
        migrations.RunPython(make_statuses),
    ]
