# Generated by Django 3.1.7 on 2021-03-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0021_auto_20210315_0541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendshipstatus',
            table='friendship_status',
        ),
    ]
