# Generated by Django 3.1.7 on 2021-03-15 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0022_auto_20210315_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'db_table': 'message_status',
            },
        ),
        migrations.AddField(
            model_name='userchats',
            name='status',
            field=models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messsage_status', to='restapis.messagestatus'),
        ),
    ]
