# Generated by Django 3.1.7 on 2021-03-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0023_auto_20210315_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchats',
            name='status',
        ),
        migrations.AddField(
            model_name='userchats',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MessageStatus',
        ),
    ]
