# Generated by Django 3.1.7 on 2021-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0024_auto_20210315_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
