# Generated by Django 3.1.7 on 2021-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0026_auto_20210316_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='image',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
