# Generated by Django 3.1.7 on 2021-03-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0027_domain_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriend',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='restapis.friendshipstatus'),
        ),
    ]
