# Generated by Django 3.1.7 on 2021-03-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('info', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.CharField(blank=True, max_length=400, null=True)),
                ('bio', models.CharField(blank=True, max_length=600, null=True)),
                ('last_seen', models.DateField()),
                ('gender', models.ForeignKey(blank=True, db_column='gender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.gender')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField()),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to='restapis.user')),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to='restapis.user')),
            ],
            options={
                'db_table': 'user_friend',
            },
        ),
        migrations.CreateModel(
            name='UserDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(blank=True, db_column='domain', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.domain')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.user')),
            ],
            options={
                'db_table': 'user_domains',
            },
        ),
    ]
