# Generated by Django 3.1.7 on 2021-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0011_userfriend_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userdomains',
            unique_together={('user', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together={('user1', 'user2')},
        ),
    ]
