# Generated by Django 3.1.7 on 2021-03-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapis', '0012_auto_20210314_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdomains',
            name='domain',
            field=models.ForeignKey(db_column='domain', on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.domain'),
        ),
        migrations.AlterField(
            model_name='userdomains',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='restapis.user'),
        ),
    ]
