domain_names = [
    "Volunteer Work",
    "Community Involvement",
    "Club Memberships",
    "Blogging",
    "Sports",
    "Art",
    "Gaming",
    "Traveling",
    "Child Care",
    "Pet Care",
    "Music",
    "Cooking",
    "Collecting",
    "Reading",
    "Classical Dance",
    "Western Dance",
    "Dance",
    "Music",
    "Singing",
    "Science fiction",
    "Painting",
    "Art",
    "Football",
    "Volleyball",
    "Chess",
    "soccer",
    "basketball",
    "tennis",
    "golf",
    "baseball",
    "volleyball",
    "running",
    "swimming",
    "badminton",
    "table tennis",
    "boxing",
    "ice skating",
    "skiing",
    "cricket",
    "roller skating",
    "pool",
    "rugby",
    "football",
    "darts",
    "ice hockey",
    "bowling",
    "karate",
    "surfing",
    "snowboarding",
    "horse racing",
    "cycling",
    "skateboarding",
    "fishing",
    "archery",
    "figure skating",
    "gymnastics",
    "sumo wrestling",
    "rock climbing",
    "fencing",
    "taekwondo",
    "jet skiing",
    "water skiing",
    "scuba diving",
    "weight lifting",
    "wind surfing",
    "judo",
    "sky diving",
    "kickboxing",
    "bungee jumping",
    "hang gliding",
]
